[package]
name = "rtlib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = {version = "0.8.4"}
num-traits = { version = "0.2.8" }

[lib]
name = "rtlib"
path = "src/lib.rs"
